config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'

  # information
  get 'home/index'
  get 'information/index'

  # user
  devise_for :users

  # book
  resources :books

  # rental
  get 'rental', to: 'rental#index'
  get 'rental/:id/addcart', to: 'rental#addcart', as: 'rental_addcart'
  get 'rental/confirmation', to: 'rental#confirmation', as: 'rental_confirmation'
  get 'rental/create', to: 'rental#create', as: 'rental_create'
  get 'rental/:id/destroy', to: 'rental#destroy', as: 'rental_destroy'
  get 'rental/lets-rental', to: 'rental#lets_rental', as: 'rental_lets_rental'
  get 'rental/show'

  # admnin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?('admin')
      can :read, :all
      can :access, :rails_admin
      can :dashboard
      if user.has_role?('superadmin')
        can :manage, :all
      else
        can :manage, []
      end
    else
      can :read, []
      can :create, []
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :lends

  mount_uploader :image, ImageUploader
  mount_uploader :bookpdf, PdfUploader

  validates :title, presence: true
  validates :bookpdf, presence: true
end

app/models/lend.rb
class Lend < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :books
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles
  has_many :lends

  def has_role?(name)
    self.roles.where(name: name).length > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :image, :bookpdf)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  def index
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index
  end
end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def addcart
    @book = Book.find params[:id]

    helpers.add @book.id
  end

  def confirmation
  end

  def create
  end

  def destroy
    helpers.delete params[:id]
    redirect_to rental_show_path
  end

  def index
    @books = Book.all
  end

  def lets_rental
    redirect_to rental_show_path if helpers.book_ids.size == 0
    @books = books
  end

  def show
    @books = books
  end

  private
  def books
    Book.where(id: helpers.book_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def rental_days
    7
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/rental_helper.rb
module RentalHelper
  def rental_book_ids
    session[:rental_book_ids]
  end

  def rental_book_ids=(value)
    session[:rental_book_ids] = value
  end

  def book_ids
    rental_book_ids.nil? ? Array.new : rental_book_ids.uniq
  end

  def add(val)
    self.rental_book_ids = book_ids << val
  end

  def delete(val)
    arr = rental_book_ids
    arr.delete(val.to_i)
    self.rental_book_ids = arr
  end

  def destroy
    self.rental_book_ids = nil
  end
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :publisher %>
    <%= f.text_field :publisher %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <div class="old field">
      <% if book.image? %>
        <%= image_tag book.image.thumb, :size => "45x45" %>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label :bookpdf %>
    <%= f.file_field :bookpdf %>
    <div class="old field">
      <% if book.bookpdf? %>
        <%= link_to "Book PDF Show", book.bookpdf.url %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><% if book.image? %>
            <%= image_tag book.image.thumb %>
            <% end %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Image:</strong>
  <% if @book.image? %>
    <%= link_to image_tag(@book.image.thumb), @book.image.url %>
  <% end %>
</p>

<p>
  <strong>Bookpdf:</strong>
  <%= link_to "Download", @book.bookpdf.url %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/information/index.html.erb
<h1>Information#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfBookshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, id: "#{key}" %>
    <% end %>

    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/rental/addcart.html.erb
<h1>Rental#addcart</h1>
<p>add to <%= @book.title %>.</p>
<%= link_to 'back to rental', rental_path %>

app/views/rental/confirmation.html.erb
<h1>Rental#confirmation</h1>

<p>
  Do you borrow <%= book_ids.size %> books for <%= rental_days %> days?
</p>
<%= link_to 'Confirm', rental_create_path %>

app/views/rental/index.html.erb
<h1>Rental</h1>
<div>
  <%= link_to "show cart", rental_show_path %>
  <%= link_to_if book_ids.size != 0, "let's rental",
        rental_lets_rental_path do end %>
  size: <%= book_ids ? book_ids.size : 0 %>
</div>

<% @books.each do |book| %>
  <h2><%= book.title%></h2>
  <% if book.image? %>
    <%= link_to image_tag(book.image.thumb), book.image.url %>
  <% else %>
    <%= link_to image_tag('Image-not-found.gif') %>
  <% end %>
  <div class="field">
    <strong>Author</strong>
    <%= book.author %>
  </div>
  <div class="field">
    <strong>Publisher</strong>
    <%= book.publisher %>
  </div>
  <%= link_to "add cart", rental_addcart_path(book) %>
  <hr />
<% end %>

app/views/rental/lets_rental.html.erb
<h1>Rental#lets_rental</h1>
<%= link_to 'return to rental', rental_path %>

<%= content_tag :p, "cart is empty." if book_ids.size == 0 %>

<%= link_to 'confirmation rental', rental_confirmation_path %>

<div>
<% @books.each do |book| %>
  <h2><%= book.title%></h2>
  <% if book.image? %>
    <%= link_to image_tag(book.image.thumb), book.image.url %>
  <% else %>
    <%= link_to image_tag('Image-not-found.gif') %>
  <% end %>
  <div class="field">
    <strong>Author</strong>
    <%= book.author %>
  </div>
  <div class="field">
    <strong>Publisher</strong>
    <%= book.publisher %>
  </div>
  <hr />
<% end %>
</div>

app/views/rental/show.html.erb
<h1>Rental#show</h1>
<%= link_to 'return to rental', rental_path %>
<%= link_to_if book_ids.size != 0, "let's rental",
      rental_lets_rental_path do end %>

<%= content_tag :p, "cart is empty." if book_ids.size == 0 %>

<% @books.each do |book| %>
  <h2><%= book.title %></h2>
  <% if book.image? %>
    <%= link_to image_tag(book.image.thumb), book.image.url %>
  <% else %>
    <%= link_to image_tag('Image-not-found.gif') %>
  <% end %>
  <div class="field">
    <strong>Author</strong>
    <%= book.author %>
  </div>
  <div class="field">
    <strong>Publisher</strong>
    <%= book.publisher %>
  </div>
  <%= link_to 'destroy this', rental_destroy_path(book), data: { confirm: 'Are you sure?' } %>
  <hr />
<% end %>